/* ==========================================================================
   ENERGÍA POSITIVA — Datos de productos
   Editá este archivo para agregar, sacar o modificar productos.
   Cada producto necesita: id, name, category, family, price, volume, tag(opcional)
   Categorías válidas: arabes, for-him, for-her, body-splash, home-spray,
                        difusor-varillas, difusor-auto
   ========================================================================== */

const CATEGORIES = [
  { key: "todos", label: "Todos" },
  { key: "arabes", label: "Árabes" },
  { key: "for-him", label: "For Him" },
  { key: "for-her", label: "For Her" },
  { key: "body-splash", label: "Body Splash" },
  { key: "home-spray", label: "Home Spray" },
  { key: "difusor-varillas", label: "Difusores de Varillas" },
  { key: "difusor-auto", label: "Difusores para Auto" },
];

const PRODUCTS = [
  {
    id: 1,
    name: "Oasis Real",
    category: "arabes",
    family: "Amaderado oriental con ámbar, vainilla y maderas preciosas",
    price: 32000,
    volume: "100cc",
    variant: "blanco",
    tag: "Más vendido",
  },
  {
    id: 2,
    name: "Desierto Nocturno",
    category: "arabes",
    family: "Oud envolvente con incienso, especias cálidas y fondo de cuero",
    price: 34000,
    volume: "100cc",
    variant: "negro",
    tag: "Más vendido",
  },
  {
    id: 3,
    name: "Jardín de Damasco",
    category: "arabes",
    family: "Floral oriental de rosa y azafrán sobre base de sándalo",
    price: 33000,
    volume: "100cc",
    variant: "blanco",
  },
  {
    id: 4,
    name: "Sultán de Ámbar",
    category: "arabes",
    family: "Amaderado especiado con cuero suave y vainilla tostada",
    price: 34500,
    volume: "100cc",
    variant: "negro",
  },
  {
    id: 5,
    name: "Cedro & Vetiver",
    category: "for-him",
    family: "Amaderado fresco con apertura cítrica y vetiver seco",
    price: 26000,
    volume: "100cc",
  },
  {
    id: 6,
    name: "Cuero Urbano",
    category: "for-him",
    family: "Amaderado intenso con cuero, tabaco y un toque especiado",
    price: 27500,
    volume: "100cc",
  },
  {
    id: 7,
    name: "Flor de Cerezo",
    category: "for-her",
    family: "Floral dulce de cerezo y peonía con fondo almizclado",
    price: 26500,
    volume: "100cc",
  },
  {
    id: 8,
    name: "Vainilla & Coco",
    category: "for-her",
    family: "Oriental dulce con vainilla cremosa y coco tropical",
    price: 27000,
    volume: "100cc",
  },
  {
    id: 9,
    name: "Body Splash Cítrico Fresco",
    category: "body-splash",
    family: "Cítrico fresco de pomelo, mandarina y un toque de menta",
    price: 12500,
    volume: "250ml",
  },
  {
    id: 10,
    name: "Body Splash Floral Suave",
    category: "body-splash",
    family: "Floral suave de jazmín y flor de azahar",
    price: 12500,
    volume: "250ml",
  },
  {
    id: 11,
    name: "Home Spray Lavanda & Vainilla",
    category: "home-spray",
    family: "Aromática relajante de lavanda francesa y vainilla",
    price: 10500,
    volume: "250ml",
  },
  {
    id: 12,
    name: "Home Spray Sándalo & Ámbar",
    category: "home-spray",
    family: "Amaderado cálido de sándalo, ámbar y fondo dulce",
    price: 10500,
    volume: "250ml",
  },
  {
    id: 13,
    name: "Difusor de Varillas Bambú Blanco",
    category: "difusor-varillas",
    family: "Fresco y limpio, notas de bambú y flor de loto",
    price: 14000,
    volume: "200ml",
  },
  {
    id: 14,
    name: "Difusor de Varillas Oud Imperial",
    category: "difusor-varillas",
    family: "Amaderado oriental de oud, incienso y especias",
    price: 15500,
    volume: "200ml",
  },
  {
    id: 15,
    name: "Difusor para Auto Cítrico Energizante",
    category: "difusor-auto",
    family: "Cítrico energizante de limón, bergamota y menta",
    price: 7500,
    volume: "unidad",
  },
];
